import {
  DatePickerRoot,
  DatePickerHeader,
  DatePickerHeading,
  DatePickerGrid,
  DatePickerCell,
  DatePickerHeadCell,
  DatePickerNext,
  DatePickerPrev,
  DatePickerGridHead,
  DatePickerGridBody,
  DatePickerGridRow,
  DatePickerCellTrigger,
  DatePickerInput,
  DatePickerCalendar,
  DatePickerField,
  DatePickerAnchor,
  DatePickerArrow,
  DatePickerClose,
  DatePickerTrigger,
  DatePickerContent,
  DatePickerMonthHeading,
  DatePickerYearHeading,
  DatePickerMonthYearOverlay,
  DatePickerOverlayItem,
} from "./components/DatePicker/index";

export const DatePicker = {
  Root: DatePickerRoot,
  Header: DatePickerHeader,
  Heading: DatePickerHeading,
  Grid: DatePickerGrid,
  Cell: DatePickerCell,
  HeadCell: DatePickerHeadCell,
  Next: DatePickerNext,
  Prev: DatePickerPrev,
  GridHead: DatePickerGridHead,
  GridBody: DatePickerGridBody,
  GridRow: DatePickerGridRow,
  CellTrigger: DatePickerCellTrigger,
  Input: DatePickerInput,
  Calendar: DatePickerCalendar,
  Field: DatePickerField,
  Anchor: DatePickerAnchor,
  Arrow: DatePickerArrow,
  Close: DatePickerClose,
  Trigger: DatePickerTrigger,
  Content: DatePickerContent,
  MonthHeading: DatePickerMonthHeading,
  YearHeading: DatePickerYearHeading,
  MonthYearOverlay: DatePickerMonthYearOverlay,
  OverlayItem: DatePickerOverlayItem,
} as const;

export default DatePicker;
